### ISSUE TITLE
Issue with main webpage

### ISSUE THREAD

**Issue by allaboutevemirolive** [fvtrx/manzil-nextjs-fe#8]
Hey @fvtrx , I am stuck on the main website and cannot find the audio button for Ayah Quran like the one you posted on Twitter. Is it still not merged?

Here is my local host. Thanks :)

![Issue_main](https://github.com/fvtrx/manzil-nextjs-fe/assets/112833599/6a91e5ab-ba6f-4938-9beb-e94286d30c7a)

**Comment by fvtrx** [comment]
Hi @allaboutevemirolive , I just merged the changes in this PR -> https://github.com/fvtrx/manzil-nextjs-fe/pull/5 for fixing issue #2 into the `main` branch.

Could you please pull the latest changes in the `main` branch? See whether it worked or not.

Thanks.

**Comment by allaboutevemirolive** [comment]
It still doesn't work on my Debian, even with the latest PR. I will try to find a workaround.

**Comment by fvtrx** [comment]
Hi @allaboutevemirolive, I think I might know what was the issue.

Can I check with you whether you had set your `process.env.NEXT_PUBLIC_QURAN_BASE_URL` value in your local .env file?

If not, then you may need to set the `NEXT_PUBLIC_QURAN_BASE_URL` in your local `.env`. Then you may retry whether the same API is successfully called and the data is able you to be retrieved from your end.

Also, you may reset your `node_modules` and clean install once again with the updated version packages just to be safe.

Let me know if the issue still persist the same.

**Comment by allaboutevemirolive** [comment]
Thank you! I didn't setup the base URL in `.env` . After getting an API from Quran.com, the issue was resolved.

Btw, should I make a PR to update README so other contributors know how to setup this too?

**Comment by fvtrx** [comment]
Yeah sure @allaboutevemirolive . My bad as well as I forgot to include the setup configuration to the `.env` in the README.md.

You may raise the PR from your branch to the `main`. Later I'll approved it.

Thanks!
